config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "events#index"
  devise_for :users
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :events, only: [:index, :new, :create, :show] do
    resources :photoevents, only: [:create]
    scope '/checkout' do
      post 'create', to: 'checkout#create', as: 'checkout_create'
      get 'success', to: 'checkout#success', as: 'checkout_success'
      get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
      resources :attendances, only: [:new, :create, :index]
    end
  end

  namespace :admin do
    root "users#index"
    resources :users, :events
  end
end

app/views/renders/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand m-1 text-warning" href="#">MaltaEvent</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Liste des évènements à Malte", root_path  %> </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Créer un nouvel évènement", new_event_path %> </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" <%= link_to "Espace admin", admin_root_path %> </a>
          </li>

          <%# Dropdown %>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-success" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Mon profil
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" <%= link_to "Mon profil", user_path(current_user) %> </a></li>
                <li><a class="dropdown-item" <%= link_to "Sign out",  destroy_user_session_path, method: :delete %></a></li>
              </ul>
              </li>
            </li>

          <% else %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle text-danger" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Sign in / Sign up
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" <%= link_to "Sign up", new_user_registration_path %>  </a></li>
                <li><a class="dropdown-item" <%= link_to "Sign in", new_user_session_path %></a></li>
              </ul>
              </li>
            </li>
            <% end %>

        </ul>
      </div>  

      <% if user_signed_in? %>
        <form class="form-inline">
          <a class="btn btn-outline-info my-2 my-sm-0 m-2" <%= link_to "Mon profil", user_path(current_user)  %> </a>
          <a class="btn btn-outline-info my-2 my-sm-0 m-2" <%= link_to "Sign out",  destroy_user_session_path, method: :delete %></a>
        </form>
      <% else %>
        <form class="form-inline">
          <a class="btn btn-outline-info my-2 my-sm-0 m-2" <%= link_to "Sign up", new_user_registration_path %> </a>    
          <a class="btn btn-outline-info my-2 my-sm-0 m-2" <%= link_to "Sign in", new_user_session_path %> </a>  
        </form>
      <% end %>  
    </div>
  </nav>