config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "events#index"
  devise_for :users
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :events, only: [:index, :new, :create, :show] do
    resources :photoevents, only: [:create]
    scope '/checkout' do
      post 'create', to: 'checkout#create', as: 'checkout_create'
      get 'success', to: 'checkout#success', as: 'checkout_success'
      get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
      resources :attendances, only: [:new, :create, :index]
    end
  end

  namespace :admin do
    root "users#index"
    resources :users, :events
  end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  # Liens entre les tables
  has_many :administrates, foreign_key: 'administrator_id', class_name: "Event"
  has_many :attendances, foreign_key: 'attendant_id'
  has_many :events, through: :attendances
  has_one_attached :avatar   

  # Mailers 
  after_create :welcome_send                                 
  def welcome_send
    UserMailer.welcome_email(self).deliver_now              
  end                                         
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # layout 'admin'
  before_action :authenticate_user!, :check_if_admin

  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_root_path

  end

  private
  def check_if_admin
    unless current_user.is_admin?
      redirect_to root_path, danger: "Vous ne pouvez pas accéder à cette page, n'étant pas administrateur, désolé !"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]
  before_action :is_that_you?, only: [:show]

  def show
    @user = User.find(params[:id])
  end

  private

  def is_that_you?
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_path
      flash[:danger] = "N'étant pas votre compte, il vous est impossible d'accéder à ce profil. Vous êtes automatiquement redirigé vers la page d'accueil"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Liste des users</h1>

app/views/users/show.html.erb
<h1>Voici ta page profil</h1>

<p>Bienvenue : <%= @user.email %></p>
<p><%= link_to "Modifier mon e-mail ou mon MdP", edit_user_registration_path  %></p><hr>

<h3>Ta photo de profil</h3>
  <% if @user.avatar.attached? %>
    <img class="img-profil img-profil-1" <%= image_tag @user.avatar, alt: 'photoevent' %>
  <% end %>
  <%= form_tag user_avatars_path(@user), multipart: true do %>         
  <%= file_field_tag :avatar %><br><br>                                     
  <%= submit_tag "Modifier ta photo de profil", class:"btn btn-success" %>                                
<% end %><hr>

<div class="m-4">
  <h2> Les évènements que tu as organisé </h2> </div>
    <div class="container border border-secondary"> 
      <div class="row border border-secondary fw-bold">
          <div class="col-4">Nom de l'évènement crée</div>    
          <div class="col-3">Ville de l'évènement</div>
          <div class="col-3">Date de l'évènement</div>           
          <div class="col-2">Nombre de participants</div>
      </div>
      <% @user.administrates.each_with_index do |event, index| %> 
                            
          <div class="row border border-light">
              <div class="col-4"><a href= "<%=event_path(event.id)%>"><%= event.title %></a></div>            
              <div class="col-3"><%= event.title %></div>
              <div class="col-3"><%= event.start_date.strftime("%d-%m-%y") %></div>         
              <div class="col-2"><%= event.attendants.count %></div>    
          </div>

      <% end %>
    </div>
</div><br>

<div class="m-4">
<h2> Les évènements auxquelles tu as participé </h2> </div>
  <div class="container border border-secondary"> 
    <div class="row border border-secondary fw-bold">
        <div class="col-4">Nom de l'évènement</div>    
        <div class="col-3">Ville de l'évènement</div>
        <div class="col-3">Date de l'évènement</div>           
        <div class="col-2">Nombre de participants</div>
    </div>
    <% @user.events.each_with_index do |event, index| %> 
                          
        <div class="row border border-light">
            <div class="col-4"><a href= "<%=event_path(event.id)%>"><%= event.title %></a></div>            
            <div class="col-3"><%= event.title %></div>
            <div class="col-3"><%= event.start_date.strftime("%d-%m-%y") %></div>         
            <div class="col-2"><%= event.attendants.count %></div>    
        </div>

    <% end %>
  </div>
<hr>