config/routes.rb
Rails.application.routes.draw do

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "events#index"
  devise_for :users
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end

  resources :events, only: [:index, :new, :create, :show] do
    resources :photoevents, only: [:create]
    scope '/checkout' do
      post 'create', to: 'checkout#create', as: 'checkout_create'
      get 'success', to: 'checkout#success', as: 'checkout_success'
      get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
      resources :attendances, only: [:new, :create, :index]
    end
  end

  namespace :admin do
    root "users#index"
    resources :users, :events
  end
end

app/models/event.rb
class Event < ApplicationRecord
  # validates :start_date, presence: true, date: {after: Proc.new { Time.now }}   
  # validate :duration_validate
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 1, :less_than_or_equal_to => 1000 } 
  validates :location, presence: true 
  validates :photoevent, presence: true

  def duration_validate
    if duration <= 0 || duration % 5 != 0
      errors.add(:duration, {message: 'Le champ doit être positif'})
    end
  end

  belongs_to :administrator, class_name: "User"
  has_many :attendances
  has_many :attendants, class_name: "User", through: :attendances
  has_one_attached :photoevent
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  # layout 'admin'
  before_action :authenticate_user!
  before_action :check_if_admin

  def index
    @events = Event.where(validated:nil)
  end

  def show
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.validated = params[:validated]
    @event.save
    if @event.validated == true
      redirect_to admin_events_path
      flash[:success] = "Event validé avec succès"
    else
      redirect_to admin_events_path
      flash[:warning] = "Event refusé avec succès"
    end
  end

  def destroy
  end

  private
  def check_if_admin
    unless current_user.is_admin?
      binding.pry
      redirect_to events_path 
      flash[:danger] = "Vous ne pouvez pas accéder à cette page, n'étant pas administrateur, désolé !"   # Marche pas (Car dans le truc du before_action ?)
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show]
  before_action :is_validated?, only: [:show]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.administrator = current_user
    if @event.save
      redirect_to events_path
      flash[:success] = "L'event a été créé avec succès, il est maintenant en attente de validation par les administrateurs" 
    else
      redirect_to new_event_path
      flash[:danger] = "L'event n'a pas pu être créé, recommence"
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  private
  def event_params
    params.require(:event).permit(:title, :description, :location, :start_date, :duration, :price, :photoevent)
  end

  def is_validated?
    @event = Event.find(params[:id])
    unless @event.validated == true
      redirect_to root_path
      flash[:danger] = "Impossible d'afficher cet évènement, il n'est pas encore validé"     # Marche pas (Car dans le truc du before_action ?)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-lg-4 mb-5">
  <div class="card h-100 shadow border-0">
    <%if event.photoevent.attached?%>
      <%= image_tag event.photoevent, alt: 'photoevent' %>
    <%else%>
      <img class="card-img-top" src="https://img.freepik.com/vecteurs-libre/date-limite-marquage-employes-homme-crayon-fixant-date-evenement-prenant-note-dans-calendrier-illustration-vectorielle-pour-calendrier-ordre-du-jour-gestion-du-temps_74855-8347.jpg?w=1380&t=st=1677450166~exp=1677450766~hmac=d28d146b0ce75c92dbae27df3829b88780ca1fcc552676dccd76090ce6bfaec8" alt="..." />
    <%end%>
    <div class="card-body p-4">
      <div class="badge bg-primary bg-gradient rounded-pill mb-2">Le <%= event.start_date.strftime("%d-%m-%Y") %></div>
   <a class="text-decoration-none link-dark stretched-link " <%= link_to "", event_path(event.id) %><div class="h5 card-title mb-3"><%= event.title %></div></a>
      <p class="card-text mb-0">L'évènement se tiendra à <%= event.location %> à <%= event.start_date.strftime("%H:%M") %></p>
    </div>
      <div class="card-footer p-4 pt-0 bg-transparent border-top-0">
          <div class="d-flex align-items-end justify-content-between">
              <div class="d-flex align-items-center">
              <% if event.administrator.avatar.attached? %>
                <img class="img-rounded" <%= image_tag event.administrator.avatar, alt: 'photoevent' %>
              <% else %>
                <img class="rounded-circle me-3" src="https://dummyimage.com/40x40/ced4da/6c757d" alt="..." />
              <% end %>
                <div class="small">
                    <div class="fw-bold">Evènement mis en ligne par <%= event.administrator.email %> </div>
                    <div class="text-muted"><%= event.created_at.strftime("%A %d %B %Y") %> </div>
                </div>
              </div>
          </div>
      </div>
  </div>
</div>



app/views/events/index.html.erb
<body class="d-flex flex-column">

  <main class="flex-shrink-0">
    <!-- Blog preview section-->
    <section class="py-5">
      <div class="container px-5">
        <h1 class="fw-bolder fs-5 mb-4">Les Evènements prévus à Malte</h1>
        <div class="row gx-5">
          <% @events.each_with_index do |event, index| %>
            <% if event.validated == true %>
              <%= render event %> 
            <% end %>
          <% end %>
        </div>
      </div>
    </section>
  </main>

app/views/events/new.html.erb
<div class="container-fluid d-flex flex-column align-items-center mt-5", style="max-width:1000px">
 <h1>Création d'un nouvel event à Malte</h1><br>
  <%= form_with model: @event do |f| %>
    <div class="form-group">
      <%= f.text_field :title, placeholder: "Titre", class: 'form-control', minlength: 5 %>
      <%= f.text_area :description, placeholder: "Description", class: 'form-control',minlength: 5, maxlength:140  %>
      <%= f.number_field :price, placeholder: "Prix", class: 'form-control', min:1  %>
      <%= f.text_field :location, placeholder: "Lieu", class: 'form-control'  %><br>
      <%= f.label "Date de début" %>
      <%= f.date_select :start_date %><br><br>
      <%= f.label "Durée en minutes" %>
      <%= f.select :duration, (5..120).step(5).to_a %><br><br>
      <%= f.label "Merci d'ajouter une photo à votre event :" %>
      <p><%= f.file_field :photoevent, class: "form-control" %></p>
      <%= f.submit "Create Event", class: "btn btn-primary"  %>
    </div>
  <% end %>
</div>

app/views/events/show.html.erb
<body>
  <div class="m-2">
    <h2>Tu souhaites participer à cet évènement ?</h2>
    <p>
    Le <%= @event.start_date.strftime("%d-%m-%y") %> se tiendra le <strong><%= @event.title %></strong> à <%= @event.location %>
    </p>

    <strong>Détails de l'évènement :</strong>
    <ul>
      <li> Description : <%= @event.description %> </li>
      <li> Evènement organisé par : <%= @event.administrator.email %> </li>
      <li> Actuellement nous sommes : <%= @event.attendants.count %> participants !  </li>
      <li> Date de début : le <%= @event.start_date.strftime("%d-%m-%y") %> à <%= @event.start_date.strftime("%H:%M") %> </li>
      <li> Il vous en coutera : <%= @event.price %>€ </li>
    </ul>

    <%= button_to "Payer pour participer à l'évènement", event_checkout_create_path(@event.id, total: @event.price), class: "btn btn-success", remote: true  %>


    <br><br>

    <% if current_user == @event.administrator %> 
    <h3>Espace admin (Uniquement visible pour le créateur de l'évènement) </h3>
    <hr>
      <p> Statut de l'évènement : 
        <% if @event.validated == true %>
          Evènement validé -> les utilisateurs du site peuvent s'y inscrire !
        <% elsif @event.validated == nil %>
          Evènement non validé -> En attente de décision des administrateurs de MaltaEvents !
        <% else %>
          Evènement refusé par les administrateurs de MaltaEvents
        <% end %>
      </p>
      <%= link_to "Voir la liste des participants à ton event", event_attendances_path(@event.id) %>
      <hr>
      <h3>Photo actuelle de l'évènement</h3>                        
        <%if @event.photoevent.attached?%>
          <img class="img-event" <%= image_tag @event.photoevent, alt: 'photoevent'%>
        <%else%>
          <p>=== Il n'y a pas encore de photo liée à cet évènement ===</p>
        <%end%>
      <hr>
        <h3>Changer la photo ?</h3>
          <%= form_tag event_photoevents_path(@event), multipart: true do %>                                                                       
          <%= file_field_tag :photoevent %> 
          <%= submit_tag "mettre à jour" %>                                 
        <% end %>
    <% end %>
    <br><br>
  </div>
</body>